version: '3'

services:
  fpm:
    build: ./fpm
    links:
      - mysql
    volumes:
      - "./magento:/var/www"
  apache:
    build: ./apache
    ports: 
      - "80:80"
    volumes:
      - "./magento:/var/www"
    links:
      - fpm
  mysql:
    image: mysql:5.6.40
    env_file: mysql.env
